INSERT INTO Role VALUES('ROLE_USER')
ON DUPLICATE KEY UPDATE name = 'ROLE_USER';	
	
INSERT INTO Role VALUES('ROLE_ADMIN')
ON DUPLICATE KEY UPDATE name = 'ROLE_ADMIN';

INSERT INTO Role VALUES('ROLE_FINAL')
ON DUPLICATE KEY UPDATE name = 'ROLE_FINAL';